var Utils=function(){};Utils.on=function(a,b,c){a!=null&&(a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c))};Utils.getContext=function(a){return typeof a.getContext=="function"?a.getContext("2d"):window.G_vmlCanvasManager.initElement(a).getContext("2d")};Utils.now=function(){return Date.now?Date.now():new Date};Utils.isLeft=function(a){return Utils.isIE8m?a.button==1:a.which==1};Utils.isRight=function(a){return Utils.isIE8m?a.button==2:a.which==3};
Utils.isWheel=function(a){return Utils.isIE8m?a.button==4:a.which==2};Utils.isFunction=function(a){return typeof a==="function"};Utils.measureText=function(a){$("body").append('<table id="m-text-table"><tr><td>'+a+"</td></tr></table>");a=$("#m-text-table").outerWidth();$("#m-text-table").remove();return a};Utils.stopEvent=function(a,b,c){!b&&a.preventDefault&&a.preventDefault();if(!c)a.cancelBubble=!0,a.returnValue=!1,a.stopPropagation&&a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation()};
Utils.quickSort=function(a,b,c){if(!(a.length<=1)){if(typeof b=="undefined"||b==null||b<0)b=0;if(typeof c=="undefined"||c==null||c<0)c=a.length-1;if(b<c){var d=Utils._partition(a,b,c);Utils.quickSort(a,b,d);Utils.quickSort(a,d+1,c)}}};Utils.swap=function(a,b,c){if(b>=a.length||c>=a.length)trace("\u8d85\u51fa\u6570\u7ec4\u4e0b\u6807\uff01");else{var d=a[b];a[b]=a[c];a[c]=d}};
Utils.max=function(a,b){if(!a||a.length==0)return null;for(var c=b?a[0][b]:a[0],d=0,e=0;e<a.length;e++){var f=b?a[e][b]:a[e];f>c&&(c=f,d=e)}return a[d]};Utils.min=function(a,b){if(!a||a.length==0)return null;for(var c=b?a[0][b]:a[0],d=0,e=0;e<a.length;e++){var f=b?a[e][b]:a[e];f<c&&(c=f,d=e)}return a[d]};Utils.minIndex=function(a,b){if(!a||a.length==0)return null;for(var c=b?a[0][b]:a[0],d=0,e=0;e<a.length;e++){var f=b?a[e][b]:a[e];f<c&&(c=f,d=e)}return d};
Utils.maxIndex=function(a,b){if(!a||a.length==0)return null;for(var c=b?a[0][b]:a[0],d=0,e=0;e<a.length;e++){var f=b?a[e][b]:a[e];f>c&&(c=f,d=e)}return d};Utils._partition=function(a,b,c){for(var d=a[b];b<c;){for(;b<c&&a[c]>=d;)--c;for(Utils.swap(a,b,c);b<c&&a[b]<=d;)++b;Utils.swap(a,b,c)}return b};Utils.equals=function(a,b){return Math.abs(a-b)<=1.0E-5};Utils._check=function(a){return a.test(navigator.userAgent.toLowerCase())};
Utils.checkUserAgent=function(){var a=navigator.userAgent.toLowerCase(),b=function(b){return b.test(a)},c=function(b,c){var d;return b&&(d=c.exec(a))?parseFloat(d[1]):0},d=document.documentMode;Utils.isOpera=b(/opera/);Utils.isOpera10_5=Utils.isOpera&&b(/version\/10\.5/);Utils.isChrome=b(/\bchrome\b/);Utils.isWebKit=b(/webkit/);Utils.isSafari=!Utils.isChrome&&b(/safari/);Utils.isSafari2=Utils.isSafari&&b(/applewebkit\/4/);Utils.isSafari3=Utils.isSafari&&b(/version\/3/);Utils.isSafari4=Utils.isSafari&&
b(/version\/4/);Utils.isSafari5_0=Utils.isSafari&&b(/version\/5\.0/);Utils.isSafari5=Utils.isSafari&&b(/version\/5/);Utils.isIE=!Utils.isOpera&&b(/msie/);Utils.isIE7=Utils.isIE&&(b(/msie 7/)&&d!=8&&d!=9&&d!=10||d==7);Utils.isIE8=Utils.isIE&&(b(/msie 8/)&&d!=7&&d!=9&&d!=10||d==8);Utils.isIE9=Utils.isIE&&(b(/msie 9/)&&d!=7&&d!=8&&d!=10||d==9);Utils.isIE10=Utils.isIE&&(b(/msie 10/)&&d!=7&&d!=8&&d!=9||d==10);Utils.isIE6=Utils.isIE&&b(/msie 6/);Utils.isIE8m=Utils.isIE6||Utils.isIE7||Utils.isIE8;Utils.isIE8p=
Utils.isIE&&!(Utils.isIE6||Utils.isIE7);Utils.isGecko=!Utils.isWebKit&&b(/gecko/);Utils.isGecko3=Utils.isGecko&&b(/rv:1\.9/);Utils.isGecko4=Utils.isGecko&&b(/rv:2\.0/);Utils.isGecko5=Utils.isGecko&&b(/rv:5\./);Utils.isGecko10=Utils.isGecko&&b(/rv:10\./);Utils.isFF3_0=Utils.isGecko3&&b(/rv:1\.9\.0/);Utils.isFF3_5=Utils.isGecko3&&b(/rv:1\.9\.1/);Utils.isFF3_6=Utils.isGecko3&&b(/rv:1\.9\.2/);Utils.isWindows=b(/windows|win32/);Utils.isMac=b(/macintosh|mac os x/);Utils.isLinux=b(/linux/);Utils.chromeVersion=
c(!0,/\bchrome\/(\d+\.\d+)/);Utils.firefoxVersion=c(!0,/\bfirefox\/(\d+\.\d+)/);Utils.ieVersion=c(Utils.isIE,/msie (\d+\.\d+)/);Utils.operaVersion=c(Utils.isOpera,/version\/(\d+\.\d+)/);Utils.safariVersion=c(Utils.isSafari,/version\/(\d+\.\d+)/);Utils.webKitVersion=c(Utils.isWebKit,/webkit\/(\d+\.\d+)/);Utils.isSecure=/^https/i.test(window.location.protocol)};
Utils.epos=function(a){if(!a)return null;var b={};return b=!a.offsetX&&!a.offsetY?{x:a.layerX,y:a.layerY}:{x:a.offsetX||a.eventX,y:a.offsetY||a.eventY}};(function(){if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a,b){for(var c=b||0;c<this.length;c++)if(this[c]===a)return c;return-1};Utils.checkUserAgent()})();var GraphicsEx=function(a){GraphicsEx.superClass.constructor.call(this,a)};Q.inherit(GraphicsEx,Q.Graphics);
GraphicsEx.prototype.dashedLine=function(a,b,c,d,e){e||(e=[5,2]);var f=e.length;this._addAction(["beginPath"]);this._addAction(["moveTo",a,b]);for(var h=c-a,g=d-b,i=g/h,g=Math.sqrt(h*h+g*g),j=0,m=!0;g>=0.1;){var k=e[j++%f];k>g&&(k=g);if(h==0){var n=d>b?1:-1;b+=k*n}else{var l=Math.sqrt(k*k/(1+i*i)),n=c>a?1:-1;a+=l*n;b+=i*l*n}m?this._addAction(["lineTo",a,b]):this._addAction(["moveTo",a,b]);g-=k;m=!m}this._addAction(["closePath"]);return this};
GraphicsEx.prototype.dashedRect=function(a,b,c,d,e){e||(e=[5,2]);this._addAction(["beginPath"]);this.dashedLine(a,b,a+c,b,e).endFill();this.dashedLine(a,b,a,b+d,e).endFill();this.dashedLine(a+c,b,a+c,b+d,e).endFill();this.dashedLine(a,b+d,a+c,b+d,e).endFill();this._addAction(["closePath"]);return this};var Element=function(a){Element.superClass.constructor.call(this,a);this.basicPainter=new GraphicsEx({width:this.width,height:this.height,x:0,y:0});this.basicPainter.visible=!1;this.selectorPainter=new GraphicsEx({width:this.width,height:this.height,x:0,y:0});this.selectorPainter.visible=!1;this.addChild(this.basicPainter);this.addChild(this.selectorPainter);this.canBeConnected=!0;this.selected=!1;this.rawType=this.baseType=null;this.id=this.name=this.state="";this.startIndex=0;this.raw=a.raw||{}};
Q.inherit(Element,Q.DisplayObjectContainer);Element.prototype.onMouseDown=function(){};Element.prototype.onMouseUp=function(){};Element.prototype.onMouseEnter=function(){};Element.prototype.onMouseLeave=function(){};Element.prototype.onMouseMove=function(){};Element.prototype.onDblClick=function(){};Element.prototype.onKeyDown=function(){};Element.prototype.select=function(){this.selected=!0;Utils.isFunction(this._drawSelector)&&this._drawSelector()};
Element.prototype.deselect=function(){this.selected=!1;if(this.selectorPainter)this.selectorPainter.visible=!1};Element.prototype.inBox=function(){};Element.prototype.remove=function(){};Element.prototype.hitTest=function(){};Element.prototype._drawBasic=function(){};Element.prototype._drawSelector=function(){};Element.prototype.getRaw=function(){return this.raw};Element.prototype.setRaw=function(a){this.raw=a};Element.prototype.rawObject=function(){};Element.prototype.getBounds=function(){};
Element.prototype.getOutgoing=function(){};Element._isActivity=function(a){return a.baseType==="task"||a.baseType==="gateway"||a.baseType==="event"||a.baseType==="container"};Element._isConnection=function(a){return a.baseType==="connection"};Element.getSelected=function(){return null};var BoxObject=function(a){BoxObject.superClass.constructor.call(this,a);this.canBeConnected=!0};Q.inherit(BoxObject,Element);
BoxObject.prototype._mouseCloseBundary=function(a,b){var c=Utils.epos(a).x,d=Utils.epos(a).y;return c<=this.x+8&&c>=this.x&&d>=this.y&&d<=this.y+8?(b("nw"),!0):c<=this.x+8&&c>=this.x&&d<=this.y+this.height&&d>=this.y+this.height-8?(b("sw"),!0):c>=this.x+this.width-8&&c<=this.x+this.width&&d<=this.y+this.height&&d>=this.y+this.height-8?(b("se"),!0):c>=this.x+this.width-8&&c<=this.x+this.width&&d>=this.y&&d<=this.y+8?(b("ne"),!0):c<=this.x+8&&c>=this.x?(b("w"),!0):c>=this.x+this.width-8&&c<=this.x+
this.width?(b("e"),!0):d>=this.y&&d<=this.y+8?(b("n"),!0):d<=this.y+this.height&&d>=this.y+this.height-8?(b("s"),!0):(b("default"),!1)};
BoxObject.prototype.onKeyDown=function(a){if(this.selected){var b=a.ctrlKey?1:5,c=a.ctrlKey?0:5;if(a.keyCode==Quark.KEY.DELETE)this.remove();else if(a.keyCode==Quark.KEY.ESC){if(this.selected=!1,this.selectorPainter.visible=!1,this.resizerPainter)this.resizerPainter.visible=!1}else a.keyCode==Quark.KEY.LEFT?this.x>c&&(this.x-=b):a.keyCode==Quark.KEY.RIGHT?this.x+this.width<this.parent.width-c&&(this.x+=b):a.keyCode==Quark.KEY.UP?this.y>c&&(this.y-=b):a.keyCode==Quark.KEY.DOWN&&this.y+this.height<
this.parent.height-c&&(this.y+=b)}};BoxObject.prototype.remove=function(){for(var a=this.parent.children.slice(0),b=0,c=a.length;b<c;b++)a[b].baseType=="connection"&&(a[b].startNode==this||a[b].endNode==this)&&this.parent.removeChild(a[b]);this.parent.removeChild(this)};BoxObject.prototype.hitTest=function(a,b){return a>=this.x&&a<=this.x+this.width&&b>=this.y&&b<=this.y+this.height};
BoxObject.prototype.inBox=function(a,b,c,d){return this.x>=a&&this.y>=b&&this.x+this.width<=a+c&&this.y+this.height<=b+d};BoxObject.prototype.boxCrossed=function(a){return this.x<=a.x+a.width&&a.x<=this.x+this.width&&this.y<=a.y+a.height&&a.y<=this.y+this.height};BoxObject.prototype.getBounds=function(){return{lowerRight:{x:this.x+this.width,y:this.y+this.height},upperLeft:{x:this.x,y:this.y}}};
BoxObject.prototype.getOutgoing=function(){for(var a=[],b=this.parent.children.slice(0),c=0;c<b.length;c++)b[c].baseType==="connection"&&b[c].startNode.id==this.id&&a.push({resourceId:b[c].id,id:b[c].id,name:b[c].name});if(this.dockedItems&&this.dockedItems.length>0)for(c=0;c<this.dockedItems.length;c++)a.push({resourceId:this.dockedItems[c].id,id:this.dockedItems[c].id,name:this.dockedItems[c].name});return a};
BoxObject.prototype.getIngoing=function(){for(var a=[],b=this.parent.children.slice(0),c=0;c<b.length;c++)b[c].baseType==="connection"&&b[c].endNode.id==this.id&&a.push({resourceId:b[c].id,id:b[c].id,name:b[c].name});return a};var FixSizeObject=function(a){FixSizeObject.superClass.constructor.call(this,a);this.mouseDown=!1;this.icon=this.mouseY=this.mouseX=null;this.baseType="";Q.merge(this,a);this.height=this.width=32};Q.inherit(FixSizeObject,BoxObject);FixSizeObject.prototype.update=function(){this._drawBasic();this.selected&&this._drawSelector()};
FixSizeObject.prototype.onMouseDown=function(a){var b=Utils.epos(a);this.mouseDown=!0;this.mouseX=b.x;this.mouseY=b.y;if(this.hitTest(b.x,b.y)){if(!this.selected)this.selected=!0;this.getStage().setChildIndex(this,this.getStage().children.length-1);a.cancelBubble=!0}else this.selected=!1,this.selectorPainter.visible=!1,a.cancelBubble=!1};FixSizeObject.prototype.onMouseUp=function(){this.mouseDown=!1};
FixSizeObject.prototype.onMouseMove=function(a){if(!Utils.isRight(a)&&!Utils.isWheel(a)){var b=Utils.epos(a),c=b.x,b=b.y,d=this.mouseX-c,e=this.mouseY-b;this.mouseX=c;this.mouseY=b;if(this.hitTest(c,b)){if(a.cancelBubble=!0,this.selected&&this.mouseDown)this.getStage().context.canvas.style.cursor="move",this.resizing=!1,this.x-d>=0&&this.x-d+this.width<=this.parent.width&&(this.x-=d),this.y-e>=0&&this.y-e+this.height<=this.parent.height&&(this.y-=e)}else a.cancelBubble=!1}};
FixSizeObject.prototype._drawBasic=function(){this.basicPainter.visible=!0;var a=new Image;a.src=this.icon;this.basicPainter.clear();this.basicPainter._addAction(["drawImage",a,0,0])};FixSizeObject.prototype._drawSelector=function(){this.selectorPainter.clear();this.selectorPainter.visible=!0;this.selectorPainter.lineStyle(1,"#ff9900").dashedRect(0,0,this.width,this.height).endFill()};var AbstractActivity=function(a){AbstractActivity.superClass.constructor.call(this,a);this.resizerPainter=new GraphicsEx({width:this.width,height:this.height,x:0,y:0});this.resizerPainter.visible=!1;this.iconPainter=new GraphicsEx({width:this.width,height:this.height,x:0,y:0});this.namePainter=new GraphicsEx({width:this.width,height:this.height,x:0,y:0});this.addChild(this.resizerPainter);this.addChild(this.iconPainter);this.addChild(this.namePainter);this.textDom=null;this.mouseDown=this.selected=
!1;this.active=a.active;this.resizable=!0;this.resizeDirect="default";this.resizing=!1;this.icon=this.border=this.mouseY=this.mouseX=null;Q.merge(this,a);this.baseType="task";this.width=a.width||120;this.height=a.height||60;this.textAlign="middle";this.iconAlign="left";this.fillColor=a.fillColor;this.dockedItems=[];this.nameBindingInput=null;this.nameInputShowing=!1};Q.inherit(AbstractActivity,BoxObject);
AbstractActivity.prototype.update=function(){if(!this.resizing&&!this.selected)this._drawBasic(),this.resizerPainter.visible=!1;else if(this.selected)this.resizing?(this._drawResizer(),this.iconPainter.visible=!1,this.namePainter.visible=!1):(this._drawBasic(),this._drawSelector(),this.resizerPainter.visible=!1);this._arrangeDocked()};
AbstractActivity.prototype.onMouseDown=function(a){var b=Utils.epos(a);this.mouseDown=!0;this.mouseX=b.x;this.mouseY=b.y;if(this.hitTest(b.x,b.y)){if(!this.selected)this.selected=!0;this.parent.setChildIndex(this,this.parent.children.length-1);a.cancelBubble=!0}else this.selected=!1,this.selectorPainter.visible=!1,a.cancelBubble=!1};AbstractActivity.prototype.onMouseUp=function(){this.mouseDown=!1;this.resizeDirect="default";this.resizing=!1};
AbstractActivity.prototype.onMouseMove=function(a){if(!Utils.isRight(a)&&!Utils.isWheel(a)){var b=Utils.epos(a),c=b.x,d=b.y,b=this.mouseX-c,e=this.mouseY-d;this.mouseX=c;this.mouseY=d;if(this.hitTest(c,d)){a.cancelBubble=!0;var f=this,c=!1;if(this.selected&&(c=this._mouseCloseBundary(a,function(a){a!="default"?(f.getStage().context.canvas.style.cursor=a+"-resize",f.resizeDirect=a):(f.getStage().context.canvas.style.cursor=a,f.resizeDirect="default")}),this.mouseDown))if(c&&this.resizeDirect!="default"&&
this.resizable&&Utils.isLeft(a))this.resizing=!0;else if(this.resizing=!1,Utils.isLeft(a))this.getStage().context.canvas.style.cursor="move",this.parent instanceof Quark.Stage?(this.x-=b,this.y-=e):(this.x-b>=0&&this.x-b+this.width<=this.parent.width&&(this.x-=b),this.y-e>=0&&this.y-e+this.height<=this.parent.height&&(this.y-=e)),this.nameInputShowing&&(c=$("#node_name_input"),this._inputXY(c))}else a.cancelBubble=!1;if(this.resizing&&this.resizable&&Utils.isLeft(a)){if(Utils.isIE8m&&this.textDom)this.textDom.style.display=
"none";var c=this.x,d=this.y,a=this.width,h=this.height;switch(this.resizeDirect){case "ne":d-=e;h+=e;a-=b;break;case "se":a-=b;h-=e;break;case "nw":d-=e;h+=e;c-=b;a+=b;break;case "sw":h-=e;c-=b;a+=b;break;case "s":h-=e;break;case "e":a-=b;break;case "n":d-=e;h+=e;break;case "w":c-=b,a+=b}if(Utils.isIE8m&&a>100&&h>60||!Utils.isIE8m&&a>60&&h>30)this.x=c,this.y=d,this.width=a,this.height=h;this.nameInputShowing&&(c=$("#node_name_input"),this._inputXY(c))}else if(Utils.isIE8m&&this.textDom&&this.visible===
!0)this.textDom.style.display="block"}};
AbstractActivity.prototype._drawBasic=function(){this.basicPainter.visible=!0;this.basicPainter.clear();this.basicPainter.hasFill=!0;this.border||this.resumeBorder();this.basicPainter.lineStyle(this.border.width,this.border.color);this.fillColor?this.basicPainter.beginFill(this.fillColor):this.basicPainter.beginLinearGradientFill(5,5,5,this.height-10,["#f6e4ad","#ffffff"],[0,1]);this.basicPainter.drawRoundRect(0,0,this.width,this.height,this.border.radius).endFill();this._drawText();this._drawIcon();
this.iconPainter.visible=!0;this.namePainter.visible=!0};
AbstractActivity.prototype._drawSelector=function(){this.selectorPainter.clear();this.selectorPainter.visible=!0;this.selectorPainter.beginFill("#ff9000").drawRect(-3,-3,6,6).endFill();this.selectorPainter.drawRect(this.width-3,this.height-3,6,6).endFill();this.selectorPainter.drawRect(-3,this.height-3,6,6).endFill();this.selectorPainter.drawRect(this.width-3,-3,6,6).endFill();this.selectorPainter.drawRect(this.width/2-3,-3,6,6).endFill();this.selectorPainter.drawRect(-3,this.height/2-3,6,6).endFill();
this.selectorPainter.drawRect(this.width/2-3,this.height-3,6,6).endFill();this.selectorPainter.drawRect(this.width-3,this.height/2-3,6,6).endFill();this.selectorPainter.lineStyle(1,"#ff9900").dashedRect(0,0,this.width,this.height).endFill()};
AbstractActivity.prototype._drawResizer=function(){this.resizerPainter.clear();this.resizerPainter.visible=!0;this.resizerPainter.lineStyle(1,"#2ebbd0").dashedRect(0,0,this.width,this.height).endFill();Utils.isIE8m||this.resizerPainter.lineStyle(0,"rgba(60, 203, 244, 0.0)").beginFill("rgba(60, 203, 244, 0.3)").drawRect(1,1,this.width-2,this.height-2).endFill();this.selectorPainter.visible=!1;this.basicPainter.visible=!1};
AbstractActivity.prototype._drawText=function(){var a=function(a){a.preventDefault();a.stopPropagation();a.stopImmediatePropagation()};if(Utils.isIE6||Utils.isIE7||Utils.isIE8){var b="text-"+this.id;$(this.getStage().context.canvas).parent();if(!this.textDom)$(this.getStage().context.canvas).parent().append(['<span id="',b,'" class="canvas-text"></span>'].join("")),this.textDom=document.getElementById(b);if(!this.visible||this.resizing)this.textDom.style.display="none";else{var c=this.parent instanceof
Quark.Stage?this.x:this.parent.x+this.x,d=this.parent instanceof Quark.Stage?this.y:this.parent.y+this.y,b=0;!this.textAlign||this.textAlign=="middle"?b=d+this.height/2-6:this.textAlign=="top"&&(b=d+3);var e=this,d=$(this.textDom).innerWidth();$(this.textDom).css({"margin-left":c+this.width/2-d/2,"margin-top":b}).html(this.name).show().bind("mousedown",function(b){a(b);var c=e.x+b.offsetX,b=e.y+b.offsetY;e.getStage().context.canvas.engine.onMouseDown({offsetX:c,offsetY:b})}).bind("mouseup",function(b){a(b);
var c=e.x+b.offsetX,b=e.y+b.offsetY;e.getStage().context.canvas.engine.onMouseUp({offsetX:c,offsetY:b})}).bind("mousemove",function(b){a(b)}).bind("dblclick",function(b){a(b);e.onDblClick({offsetX:e.x+b.offsetX,offsetY:e.y+b.offsetY})}).bind("keydown",function(b){a(b);if(b.keyCode!=Q.KEY.DELETE||confirm("\u786e\u5b9a\u5220\u9664\u9009\u4e2d\u7684\u5bf9\u8c61\u5417\uff1f"))e.onKeyDown(b)}).bind("contextmenu",function(b){a(b);var c=e.x+b.offsetX,b=e.y+b.offsetY;e.getStage().context.canvas.engine.menu.showAt({offsetX:c,
offsetY:b});return!1})}}else c=this.getStage().context.canvas.getContext("2d").measureText(this.name).width,this.namePainter.clear(),b=0,!this.textAlign||this.textAlign=="middle"?b=this.height/2+6:this.textAlign=="top"&&(b=14),this.namePainter._addAction(["font","12px serif"])._addAction(["fillText",this.name,this.width/2-c/2,b])};
AbstractActivity.prototype._drawIcon=function(){if(this.icon){var a=new Image;a.src=this.icon;this.iconPainter.clear();var b;this.iconAlign=="left"?b=3:this.iconAlign=="center"?b=this.width/2-8:this.iconAlign=="right"&&(b=this.width-18);this.iconPainter._addAction(["drawImage",a,b,3])}};AbstractActivity.prototype.remove=function(){this.textDom&&$(this.textDom).remove();AbstractActivity.superClass.remove.call(this)};
AbstractActivity.prototype.onDblClick=function(a){var b=Utils.epos(a).x,c=Utils.epos(a).y;if(this.hitTest(b,c)){var d=$("#node_name_input");d.get(0)==null&&($(this.getStage().context.canvas).parent().append("<input id='node_name_input' class='canvas-textfield'></input>"),d=$("#node_name_input"));var e=this;d.unbind("keydown").bind("keydown",function(a){if(Quark.KEY.ENTER==a.keyCode){if(e.name=d.val(),d.hide(0,function(){e.nameInputShowing=!1}),e._drawText(),e.nameBindingInput)Utils.isFunction(e.nameBindingInput.setValue)?
e.nameBindingInput.setValue(e.name):e.nameBindingInput.value=e.name}else Quark.KEY.ESC==a.keyCode&&d.hide(0,function(){e.nameInputShowing=!1})});d.unbind("blur").bind("blur",function(){d.hide(0,function(){e.nameInputShowing=!1});e._drawText();if(e.nameBindingInput)Utils.isFunction(e.nameBindingInput.setValue)?e.nameBindingInput.setValue(e.name):e.nameBindingInput.value=e.name});e._inputXY(d).show(0,function(){e.nameInputShowing=!0});d.focus().val(this.name).select();a.cancelBubble=!0}};
AbstractActivity.prototype._inputXY=function(a){var b=this.parent instanceof Quark.Stage?this.y:this.parent.y+this.y;a.css({"margin-left":(this.parent instanceof Quark.Stage?this.x:this.parent.x+this.x)+this.width/2-a.innerWidth()/2,"margin-top":b+this.height/2-a.innerHeight()/2});return a};AbstractActivity.prototype.setBorder=function(a){Q.merge(this.border,a)};AbstractActivity.prototype.resumeBorder=function(){this.border=this.active?{width:3,radius:8,color:"#FA6042"}:{width:1,radius:8,color:"#333333"}};
AbstractActivity.prototype.setActive=function(a,b){this.active=a;b?this.border=b:this.resumeBorder()};AbstractActivity.prototype.addDockedItem=function(a){for(var b=0;b<this.dockedItems.length;b++)if(a.id===this.dockedItems[b].id)return;this.dockedItems.push(a)};AbstractActivity.prototype.removeDockedItem=function(a){for(var b=[],c=0;c<this.dockedItems.length;c++)a.id!=this.dockedItems[c].id&&b.push(this.dockedItems[c]);this.dockedItems=b};
AbstractActivity.prototype.setNameBindingInput=function(a){this.nameBindingInput=a};
AbstractActivity.prototype._arrangeDocked=function(){for(var a=0;a<this.dockedItems.length;a++){var b=this.parent.getChildIndex(this),c=this.parent.getChildIndex(this.dockedItems[a]);b>c&&this.parent.swapChildren(this,this.dockedItems[a])}for(var b=[],c=[],d=[],e=[],a=0;a<this.dockedItems.length;a++){var f=this.dockedItems[a];f.posName==="B"&&b.push(f);f.posName==="R"&&c.push(f);f.posName==="L"&&d.push(f);f.posName==="T"&&e.push(f)}if(b.length>0)for(a=0;a<b.length;a++)if(!b[a].selected)b[a].y=this.y+
this.height-b[a].height/2,b[a].x=this.x+b[a].offsetX;if(c.length>0)for(a=0;a<c.length;a++)if(!c[a].selected)c[a].x=this.x+this.width-c[a].width/2,c[a].y=this.y+c[a].offsetY;if(d.length>0)for(a=0;a<d.length;a++)if(!d[a].selected)d[a].x=this.x-d[a].width/2,d[a].y=this.y+d[a].offsetY;if(e.length>0)for(a=0;a<e.length;a++)if(!e[a].selected)e[a].y=this.y-e[a].height/2,e[a].x=this.x+e[a].offsetX};var AbstractTask=function(a){AbstractTask.superClass.constructor.call(this,a);this.baseType="task"};Q.inherit(AbstractTask,AbstractActivity);var AbstractEvent=function(a){AbstractEvent.superClass.constructor.call(this,a);this.baseType="event"};Q.inherit(AbstractEvent,FixSizeObject);var AbstractGateway=function(a){AbstractGateway.superClass.constructor.call(this,a);this.baseType="gateway"};Q.inherit(AbstractGateway,FixSizeObject);var AbstractConnection=function(a){this.points=a.points?a.points:[];this.mPoints=[];AbstractConnection.superClass.constructor.call(this,a);if(typeof a.startNode==="string")for(var b=this.parent.children.slice(0),c=0;c<b.length;c++){if(Element._isActivity(b[c])&&b[c].id===a.startNode){this.startNode=b[c];break}}else this.startNode=a.startNode;if(typeof a.endNode==="string"){b=this.parent.children.slice(0);for(c=0;c<b.length;c++)if(Element._isActivity(b[c])&&b[c].id===a.endNode){this.endNode=b[c];break}}else this.endNode=
a.endNode;this._destinations();this.arrowH=12;this.arrowW=8;this.painter=new Q.Graphics;this.addChild(this.painter);this.condition=null;this.draging=!1;this.dragingPoint=null;this.selected=!1;this.baseType="connection";this.canBeConnected=!1};Q.inherit(AbstractConnection,Element);
AbstractConnection.prototype.update=function(){this.points&&!(this.points.length<=0)&&(this._destinations(),this.painter.clear(),this.selected?(this._calcMiddle(),this._drawSelector()):this._drawBasic(this._isDefault()?"#D9442F":"#111111"),this._drawText())};AbstractConnection.prototype.onMouseDown=function(a){if(Utils.isLeft(a)){var b=Utils.epos(a),b=this.hitTest(b.x,b.y);if(this.selected&&b)this.draging=b;this.selected=b;a.cancelBubble=b}};
AbstractConnection.prototype.onMouseMove=function(a){if(this.startNode.id!=this.endNode.id&&this.draging&&this.selected){var b=a.offsetX||a.eventX,a=a.offsetY||a.eventY;if(this.dragingPoint==null)for(var c=0;c<this.points.length;c++){var d=this.points[c].x-b,e=this.points[c].y-a,d=Math.sqrt(d*d+e*e);if(d<5||c==this.points.length-1&&d<12){this.dragingPoint=c;break}}if(this.dragingPoint!=null)this.points[this.dragingPoint].x=b,this.points[this.dragingPoint].y=a,this._calcMiddle();else for(c=0;c<this.mPoints.length;c++)if(d=
this.mPoints[c].x-b,e=this.mPoints[c].y-a,d=Math.sqrt(d*d+e*e),d<5){this.dragingPoint=this._addCorner(this.mPoints[c].after,b,a);this._calcMiddle();break}}};
AbstractConnection.prototype.onMouseUp=function(){this._join();for(var a=1;a<this.points.length;a++){if(this.points[a-1]){var b=Math.atan((this.points[a-1].y-this.points[a].y)/(this.points[a-1].x-this.points[a].x))/2/Math.PI*360;if(90-Math.abs(b)<5)this.points[a].x=this.points[a-1].x;if(Math.abs(b)<5)this.points[a].y=this.points[a-1].y}if(this.points[a+1]){b=Math.atan((this.points[a].y-this.points[a+1].y)/(this.points[a].x-this.points[a+1].x))/2/Math.PI*360;if(90-Math.abs(b)<5)this.points[a].x=this.points[a+
1].x;if(Math.abs(b)<5)this.points[a].y=this.points[a+1].y}this._calcMiddle()}this.draging=!1;this.dragingPoint=null};AbstractConnection.prototype.onKeyDown=function(a){if(this.selected)a.keyCode==Quark.KEY.ESC?(this.draging=this.selected=!1,this.dragingPoint=null):a.keyCode==Quark.KEY.DELETE&&this.remove()};
AbstractConnection.prototype._destinations=function(){if(this.startNode&&this.endNode)if(this.startNode.id==this.endNode.id)this.points=[],this.points.push({x:this.startNode.x+this.startNode.width/2,y:this.startNode.y}),this.points.push({x:this.startNode.x+this.startNode.width/2,y:this.startNode.y-20}),this.points.push({x:this.startNode.x+this.startNode.width+20,y:this.startNode.y-20}),this.points.push({x:this.startNode.x+this.startNode.width+20,y:this.startNode.y+this.startNode.height/2}),this.points.push({x:this.startNode.x+
this.startNode.width,y:this.startNode.y+this.startNode.height/2});else{if(this.points.length==0){var a=this.endNode.x+this.endNode.width/2,b=this.endNode.y+this.endNode.height/2;this.points.push({x:this.startNode.x+this.startNode.width/2,y:this.startNode.y+this.startNode.height/2});this.points.push({x:a,y:b})}var a=this._calcHit(this.points[1],this.startNode),b=this.points.length,c=this._calcHit(this.points[b-2],this.endNode);a&&(this.points[0]=a);c&&(this.points[b-1]=c)}};
AbstractConnection.prototype._calcHit=function(a,b){var c=[];if(!a||!b)return trace("\u53c2\u8003\u7ebf\u6bb5\u4e0d\u5b58\u5728\u6216\u8005\u53c2\u8003\u8282\u70b9\u4e0d\u5b58\u5728\uff01"),null;var d=a.x,e=a.y,f=b.x+b.width/2,h=b.y+b.height/2;c.push(this._calcCross(d,e,f,h,b.x,b.y,b.x+b.width,b.y));c.push(this._calcCross(d,e,f,h,b.x,b.y,b.x,b.y+b.height));c.push(this._calcCross(d,e,f,h,b.x+b.width,b.y,b.x+b.width,b.y+b.height));c.push(this._calcCross(d,e,f,h,b.x,b.y+b.height,b.x+b.width,b.y+b.height));
d=[];for(e=0;e<c.length;e++)(f=c[e])&&f.x>=b.x-1&&f.x<=b.x+b.width+1&&f.y>=b.y-1&&f.y<=b.y+b.height+1&&d.push({p:f,d:Math.sqrt((f.x-a.x)*(f.x-a.x)+(f.y-a.y)*(f.y-a.y))});return d.length==0?null:(c=Utils.min(d,"d"))?c.p:null};AbstractConnection.prototype._calcCross=function(a,b,c,d,e,f,h,g){if(a-c==0&&e-h==0)return null;if(b-d==0&&f-g==0)return null;b=(d*a-b*c)/(a-c);d=(d-b)/c;f=(g*e-f*h)/(e-h);g=(g-f)/h;a==c?c=g*a+f:(a=e==h?e:(f-b)/(d-g),c=d*a+b);return{x:a,y:c}};
AbstractConnection.prototype._calcMiddle=function(){this.mPoints=[];for(var a=0;a<this.points.length-1;a++)this.mPoints.push({x:this.points[a].x+(this.points[a+1].x-this.points[a].x)/2,y:this.points[a].y+(this.points[a+1].y-this.points[a].y)/2,after:a})};
AbstractConnection.prototype._drawSelector=function(){if(this.startNode.id==this.endNode.id)this._drawBasic("#ff9000");else{this.painter.lineStyle(1,"#ff9000");this.painter.beginPath()._addAction(["moveTo",this.points[0].x,this.points[0].y]);for(var a=1;a<this.points.length;a++)this.painter._addAction(["lineTo",this.points[a].x,this.points[a].y]);this.painter.endFill();if(!this.mPoints)this.mPoints=[];for(a=0;a<this.mPoints.length;a++)this.painter.beginFill("#ff9900").beginPath()._addAction(["arc",
this.mPoints[a].x,this.mPoints[a].y,3,0,Math.PI*2]).closePath().endFill(),this.painter.hasFill=!1;for(a=0;a<this.points.length-1;a++)this.painter.beginPath().beginFill("#ffffff")._addAction(["arc",this.points[a].x,this.points[a].y,4,0,Math.PI*2]).closePath().endFill(),this.painter.hasFill=!1;this._drawArrow()}};
AbstractConnection.prototype._drawText=function(){if(this.name&&!Utils.isIE6){for(var a=0,b=0,c=0;c<this.points.length-1;c++){if(!this.points[c+1])return;var d=this.points[c],e=this.points[c+1],d=Math.sqrt((d.x-e.x)*(d.x-e.x)+(d.y-e.y)*(d.y-e.y));d>b&&(b=d,a=c)}a==0?(c=this.startNode.x+this.startNode.width/2,d=this.startNode.y+this.startNode.height/2):(c=this.points[a].x,d=this.points[a].y);var f=c,h=this.points[a+1].x,e=Math.atan((this.points[a+1].y-d)/(h-f)),g=this.getStage().context.canvas.getContext("2d").measureText(this.name).width;
Utils.isIE8m&&(g*=1.5);a=h>f?a==0?this.startNode.width/2+10:b/2-g/2:a==0?-this.startNode.width/2-b/2-g/2-10:b/2-g/2;this.painter._addAction(["font","12px serif"])._addAction(["translate",c,d])._addAction(["rotate",e])._addAction(["fillText",this.name,a,-10])}};
AbstractConnection.prototype._drawBasic=function(a){a||(a="#111111");this.painter.lineStyle(1,a);this.painter.beginPath()._addAction(["moveTo",this.points[0].x,this.points[0].y]);for(var b=1;b<this.points.length-1;b++){var c=this.points[b-1].x,d=this.points[b-1].y,e=this.points[b].x,f=this.points[b].y,f=(f-d)/(e-c),h=Math.atan(f),f=Math.cos(h)*10,h=Math.sin(h)*10,g=1;c>e&&(g=-1);var i=this.points[b].x-g*f,j=this.points[b].y-g*h;this.painter._addAction(["lineTo",i,j]);c=this.points[b].x;d=this.points[b].y;
e=this.points[b+1].x;f=this.points[b+1].y;f=(f-d)/(e-c);h=Math.atan(f);f=Math.cos(h)*10;h=Math.sin(h)*10;g=1;c>e&&(g=-1);this.painter._addAction(["bezierCurveTo",i,j,c,d,this.points[b].x+g*f,this.points[b].y+g*h])}this.painter._addAction(["lineTo",this.points[b].x,this.points[b].y]);this.painter.endFill();this._drawArrow(a)};
AbstractConnection.prototype._drawArrow=function(a){var b=this.points[this.points.length-2].x,c=this.points[this.points.length-1].x,d=this.points[this.points.length-1].y,e=(d-this.points[this.points.length-2].y)/(c-b),f=Math.atan(e)+Math.PI/9,e=Math.atan(e)-Math.PI/9,h=-1;b>c&&(h=1);var b=c+h*Math.cos(f)*10,f=d+h*Math.sin(f)*10,g=c+h*Math.cos(e)*10,e=d+h*Math.sin(e)*10;this.selected?this.painter.beginFill("#ff9900"):this.painter.beginFill(a);this.painter.beginPath()._addAction(["moveTo",c,d])._addAction(["lineTo",
b,f])._addAction(["lineTo",g,e]).closePath().endFill();this.painter.hasFill=!1};AbstractConnection.prototype._addCorner=function(a,b,c){for(var d=[],e=null,f=0;f<this.points.length;f++)d.push(this.points[f]),f==a&&(d.push({x:b,y:c}),e=f+1);this.points=d;return e};AbstractConnection.prototype._delCorner=function(a){for(var b=[],c=0;c<this.points.length;c++)c!=a&&b.push(this.points[c]);this.points=b};
AbstractConnection.prototype._join=function(){for(var a=1;a<this.points.length-1;a++){var b=(this.points[a-1].y-this.points[a].y)/(this.points[a-1].x-this.points[a].x),c=(this.points[a].y-this.points[a+1].y)/(this.points[a].x-this.points[a+1].x);if(b==c||Math.abs(b-c)<0.15||isNaN(b)&&isNaN(c)){this._delCorner(a);this._calcMiddle();this._join();break}}};
AbstractConnection.prototype._isDefault=function(){return this.startNode&&this.startNode.raw&&this.startNode.raw.defaultFlow?this.startNode.raw.defaultFlow===this.id:!1};AbstractConnection.prototype.remove=function(){try{this.parent.removeChild(this)}catch(a){}};
AbstractConnection.prototype.inBox=function(a,b,c,d){if(!this.points||this.points.length==0)return!1;var e=this.points[0].x,f=this.points[0].y,h=e>=a&&f>=b&&e<=a+c&&f<=b+d,f=this.points.length,e=this.points[f-1].x,f=this.points[f-1].y;return h&&e>=a&&f>=b&&e<=a+c&&f<=b+d};
AbstractConnection.prototype.hitTest=function(a,b){for(var c=0;c<this.points.length-1;c++){var d,e=this.points[c].x>this.points[c+1].x?this.points[c+1].x:this.points[c].x,f=this.points[c].x>this.points[c+1].x?this.points[c].x:this.points[c+1].x,h=this.points[c].y>this.points[c+1].y?this.points[c+1].y:this.points[c].y,g=this.points[c].y>this.points[c+1].y?this.points[c].y:this.points[c+1].y,i=(this.points[c].x-this.points[c+1].x)/(this.points[c].y-this.points[c+1].y);Utils.equals(e,f)?d=a-e:Utils.equals(h,
g)?d=b-h:(d=Math.abs(Math.abs(i*(b-this.points[c].y)+this.points[c].x)-a),i=Math.abs(Math.abs(1/i*(a-this.points[c].x)+this.points[c].y)-b),d=d*i/Math.sqrt(d*d+i*i));if((isNaN(d)||Math.abs(d)<10)&&a>=e-2&&a<=f+2&&b>=h-2&&b<=g+2)return!0}return!1};AbstractConnection.prototype.getBounds=function(){return{lowerRight:{x:Utils.max(this.points,"x").x,y:Utils.max(this.points,"y").y},upperLeft:{x:Utils.min(this.points,"x").x,y:Utils.min(this.points,"y").y}}};
AbstractConnection.prototype.getOutgoing=function(){return[{resourceId:this.endNode.id,id:this.endNode.id,name:this.endNode.name}]};var AbstractContainer=function(a){AbstractContainer.superClass.constructor.call(this,a);this.baseType="container";this.icon=null;this.name=a.name||"Container";this.textAlign="top";this.autoSize=!0;this.plusPainter=new GraphicsEx({width:this.width,height:this.height,x:0,y:0});this.minusPainter=new GraphicsEx({width:this.width,height:this.height,x:0,y:0});this.addChild(this.plusPainter);this.addChild(this.minusPainter);this.maximized=!0;this.plusPainter.visible=!this.maximized;this.minusPainter.visible=
this.maximized;this.startIndex=this.children.length-1;this.realWidth=this.width;this.realHeight=this.height;this.defaultWidth=this.width;this.defaultHeight=this.height};Q.inherit(AbstractContainer,AbstractActivity);
AbstractContainer.prototype.update=function(a){AbstractContainer.superClass.update.call(this,a);this._drawTools();this.resizing?(this.plusPainter.visible=!1,this.minusPainter.visible=!1):(this.plusPainter.visible=!this.maximized,this.minusPainter.visible=this.maximized);for(var a=this.children.slice(0),b=0;b<a.length;b++)if(a[b].baseType&&(a[b].visible=this.maximized,Utils.isIE8m&&a[b].textDom))a[b].textDom.style.display=a[b].resizing?"none":this.maximized?"block":"none"};
AbstractContainer.prototype.onMouseDown=function(a){if(this._delegate({event:a,method:"onMouseDown",onBefore:function(a){a.selected=!1;a.selectorPainter.visible=!1}}))this.selected=!1,this.selectorPainter.visible=!1;else{var b=this._convertEvent(a);this._inTools(b.x,b.y)?this.maximized?this.minimize():this.maximize():AbstractContainer.superClass.onMouseDown.call(this,a)}};
AbstractContainer.prototype.onMouseMove=function(a){if(!this._delegate({event:a,method:"onMouseMove"})){var b=this._convertEvent(a);this._inTools(b.x,b.y)?this.getStage().context.canvas.style.cursor="pointer":(this.getStage().context.canvas.style.cursor="default",AbstractContainer.superClass.onMouseMove.call(this,a))}};AbstractContainer.prototype.onMouseUp=function(a){this._delegate({event:a,method:"onMouseUp"})||AbstractContainer.superClass.onMouseUp.call(this,a)};
AbstractContainer.prototype.onKeyDown=function(a){for(var b=this.children.slice(0),c=0;c<b.length;c++){var d=b[c];if(Element._isActivity(d)||d.baseType==="connection")d.onKeyDown(a)}AbstractContainer.superClass.onKeyDown.call(this,a)};AbstractContainer.prototype.onDblClick=function(a){if(!this._delegate({event:a,method:"onDblClick"})){var b=this._convertEvent(a);this._inTools(b.x,b.y)||AbstractContainer.superClass.onDblClick.call(this,a)}};AbstractContainer.prototype.addItem=function(a){this.addChild(a)};
AbstractContainer.prototype.getSelected=function(){for(var a=this.children.slice(0),b=[],c=0;c<a.length;c++){var d=a[c];if(d&&(d.selected&&b.push(d),Utils.isFunction(d.getSelected)&&(d=d.getSelected())))for(var e=0;e<d.length;e++)b.push(d[e])}return b};
AbstractContainer.prototype.getSelectedNodes=function(){for(var a=this.children.slice(0),b=[],c=0;c<a.length;c++){var d=a[c];Element._isActivity(d)&&d.selected&&b.push(d);if(Utils.isFunction(d.getSelectedNodes)&&(d=d.getSelectedNodes()))for(var e=0;e<d.length;e++)b.push(d[e])}return b};AbstractContainer.prototype.getNodes=function(){for(var a=this.children.slice(0),b=[],c=0;c<a.length;c++){var d=a[c];b.push(d);if(Utils.isFunction(d.getNodes)&&(d=d.getNodes()))for(var e=0;e<d.length;e++)b.push(d[e])}return b};
AbstractContainer.prototype.maximize=function(){var a=Math.abs(this.width-this.realWidth),b=Math.abs(this.height-this.realHeight);this.width=this.realWidth;this.height=this.realHeight;this.maximized=!0;for(var c=this.parent.children.slice(0),d=0;d<c.length;d++){var e=c[d];e.baseType&&e.baseType!="connection"&&e.id!=this.id&&(e.x>this.x+this.defaultWidth&&(e.x+=a),e.y>this.y+this.defaultHeight&&(e.y+=b))}};
AbstractContainer.prototype.minimize=function(){this.realHeight=this.height;this.realWidth=this.width;this.width=this.defaultWidth;this.height=this.defaultHeight;this.maximized=!1;for(var a=Math.abs(this.width-this.realWidth),b=Math.abs(this.height-this.realHeight),c=this.parent.children.slice(0),d=0;d<c.length;d++){var e=c[d];e.baseType&&e.baseType!="connection"&&e.id!=this.id&&(e.x>this.x+this.realWidth&&(e.x-=a),e.y>this.y+this.realHeight&&(e.y-=b))}};
AbstractContainer.prototype._convertEvent=function(a){var b=Utils.epos(a),c=b.x-this.x,b=b.y-this.y,d={};Q.merge(d,a);d.offsetX=c;d.offsetY=b;d.x=c;d.y=b;return d};AbstractContainer.prototype._drawTools=function(){var a=new Image;a.src=Icons.plus;this.plusPainter.clear();this.plusPainter._addAction(["drawImage",a,this._toolsRange().x,this._toolsRange().y]);a=new Image;a.src=Icons.minus;this.minusPainter.clear();this.minusPainter._addAction(["drawImage",a,this._toolsRange().x,this._toolsRange().y])};
AbstractContainer.prototype._toolsRange=function(){return{x:this.width-21,y:5,width:16,height:16}};AbstractContainer.prototype._inTools=function(a,b){var c=this._toolsRange();return a>=c.x&&a<=c.x+c.width&&b>=c.y&&b<=c.y+c.height};
AbstractContainer.prototype._delegate=function(a){for(var b=this._convertEvent(a.event),c=!1,d=this.children.slice(0),e=0;e<d.length;e++){var f=d[e];Utils.isFunction(a.onBefore)&&Element._isActivity(f)&&a.onBefore.call(this,f);Element._isActivity(f)?f.hitTest(b.x,b.y)&&Utils.isFunction(f[a.method])&&(f[a.method](b),c=!0,Utils.isFunction(a.onAfter)&&a.onAfter.call(this,f)):f.baseType=="shadow"?(f[a.method](b),c=!1):f.baseType=="connection"&&(f[a.method](b),f.hitTest(b.x,b.y)&&(c=!0))}return c};
AbstractContainer.prototype.getBounds=function(){return{lowerRight:{x:this.x+Utils.max([this.realWidth,this.width]),y:this.y+Utils.max([this.realHeight,this.height])},upperLeft:{x:this.x,y:this.y}}};var ShadowFlow=function(a){ShadowFlow.superClass.constructor.call(this,a);this.startX=a.startX;this.startY=a.startY;this.endX=this.startX;this.endY=this.startY;this.removeOnComplete=a.removeOnComplete;this.ghostLine=new GraphicsEx({x:this.x,y:this.y,width:this.width,height:this.height});this.ghostLine.visible=!1;this.addChild(this.ghostLine);this.baseType="shadow";this.rawType="shadowFlow";this.inBox=this.begin=!1;this.startNode=this.overNode=null;this.connectionCreated=a.connectionCreated;this.canBeConnected=
!1};Q.inherit(ShadowFlow,Q.DisplayObjectContainer);ShadowFlow.create=function(a,b){var c={id:Quark.UIDUtil.createUID("shadowFlow"),x:0,y:0,autoSize:!0};a&&Q.merge(c,a);c=new ShadowFlow(c);c.visible=!0;if(b)c.startNode=b,c.begin=!0,c.startX=b.x+b.width/2,c.startY=b.y+b.height/2;return c};
ShadowFlow.prototype.onMouseMove=function(a){a.cancelBubble=!0;a=Utils.epos(a);if(a.x>=0&&a.x<=this.parent.width)this.endX=a.x;if(a.y>=0&&a.y<=this.parent.height)this.endY=a.y;if(a=this._getCurrentBox())this.inBox=!0,Utils.isIE8m?this.getStage().context.canvas.style.cursor="pointer":this.getStage().context.canvas.style.cursor="url('"+Icons.plug+"'), auto",Utils.isFunction(a.setBorder)&&a.setBorder({color:"#ff0000"}),this.overNode=a;else if(this.inBox=!1,Utils.isIE8m?this.getStage().context.canvas.style.cursor=
"no-drop":this.getStage().context.canvas.style.cursor="url('"+Icons.plugDisable+"'), auto",this.overNode&&Utils.isFunction(this.overNode.resumeBorder))this.overNode.resumeBorder(),this.overNode=null};
ShadowFlow.prototype.onMouseDown=function(a){var b=Utils.epos(a);a.cancelBubble=!0;a=this._getCurrentBox();if(this.begin){if(this.begin&&a&&a&&this.startNode)Utils.isFunction(a.resumeBorder)&&a.resumeBorder(),b=new AbstractConnection({x:0,y:0,autoSize:!0,startNode:this.startNode,endNode:a}),Utils.isFunction(this.connectionCreated)?this.connectionCreated.call(this,b):b.id=Quark.UIDUtil.createUID("connection"),this.parent.addChild(b),this.getStage().context.canvas.style.cursor="default",this.begin=
!1,this.startNode=null,this.removeOnComplete&&this.parent.removeChild(this)}else if(a)this.begin=!0,this.startNode=a,this.startX=a.x+a.width/2,this.startY=a.y+a.height/2,this.endX=b.x,this.endY=b.y};ShadowFlow.prototype.onMouseUp=function(a){a.cancelBubble=!0};ShadowFlow.prototype.onKeyDown=function(a){if(a.keyCode==Quark.KEY.ESC)this.getStage().context.canvas.style.cursor="default",this.parent.removeChild(this)};
ShadowFlow.prototype.update=function(){this.begin?(this.ghostLine.visible=!0,this.ghostLine.clear(),this.ghostLine.lineStyle(1,"#ff9000"),this.ghostLine.dashedLine(this.startX,this.startY,this.endX,this.endY).endFill()):this.ghostLine.visible=!1};ShadowFlow.prototype._getCurrentBox=function(){for(var a=this.endX,b=this.endY,c=this.parent.children.slice(0),d=null,e=0,f=c.length;e<f;e++)if(Element._isActivity(c[e])&&c[e].hitTest(a,b)){d=c[e];break}return d};var ShadowBox=function(a){ShadowBox.superClass.constructor.call(this,a);this.startX=a.startX;this.startY=a.startY;this.ghostBox=new GraphicsEx({x:this.x,y:this.y,width:this.width,height:this.height});this.ghostBox.visible=!1;this.addChild(this.ghostBox);this.baseType="shadow";this.rawType="shadowFlow";this.state="inited"};Q.inherit(ShadowBox,Q.DisplayObjectContainer);
ShadowBox.create=function(a){return new ShadowBox({id:Quark.UIDUtil.createUID("shadowBox"),x:0,y:0,startX:a.offsetX||a.eventX,startY:a.offsetY||a.eventY,endX:a.offsetX||a.eventX,endY:a.offsetY||a.eventY})};
ShadowBox.prototype.onMouseMove=function(a){var b=this.parent.children;if(b)for(var c=0;c<b.length;c++)if(b[c].selected){this.visible=!0;this.parent.removeChild(this);return}this.width=(a.offsetX||a.eventX)-this.startX;this.height=(a.offsetY||a.eventY)-this.startY;this.endX=a.offsetX||a.eventX;this.endY=a.offsetY||a.eventY;this.getStage().context.canvas.style.cursor="crosshair"};
ShadowBox.prototype.update=function(){this.visible=!0;this.ghostBox.clear();this.ghostBox.visible=!0;this.ghostBox.lineStyle(1,"#ff9000").dashedRect(this.startX,this.startY,this.width,this.height).endFill()};
ShadowBox.prototype.onMouseUp=function(){for(var a=this.parent.children,b=0;b<a.length;b++){var c=a[b];if(typeof c.inBox=="function"&&Element._isActivity(c)){var d=this.startX;this.width<0&&(d=this.startX+this.width);var e=this.startY;this.height<0&&(e=this.startY+this.height);c.inBox(d,e,Math.abs(this.width),Math.abs(this.height))&&typeof c.select=="function"&&c.select()}}this.getStage().context.canvas.style.cursor="default";this.parent.removeChild(this)};var DockableObject=function(a){DockableObject.superClass.constructor.call(this,a);this.baseType="event";if(a.dockTarget&&Utils.isFunction(a.dockTarget.addDockedItem))this.dockTarget=a.dockTarget;this.posName=null;this.offsetY=this.offsetX=0;this.docked=!1};Q.inherit(DockableObject,FixSizeObject);
DockableObject.prototype.onMouseUp=function(a){DockableObject.superClass.onMouseUp.call(this,a);a=Utils.epos(a);if(this.hitTest(a.x,a.y)){a=this.parent.children.slice(0);this.docked=!1;for(var b=0;b<a.length;b++)if(a[b].id!==this.id&&this.boxCrossed(a[b])&&Utils.isFunction(a[b].addDockedItem)){this._dock(a[b]);Utils.isFunction(a[b].resumeBorder)&&a[b].resumeBorder();this.docked=!0;break}if(!this.docked&&this.dockTarget)this.dockTarget.removeDockedItem(this),this.dockTarget=null}};
DockableObject.prototype.onMouseMove=function(a){DockableObject.superClass.onMouseMove.call(this,a);if(!this.dockTarget&&(a=Utils.epos(a),this.hitTest(a.x,a.y)))for(var a=this.parent.children.slice(0),b=null,c=0;c<a.length;c++)a[c].id!==this.id&&(this.boxCrossed(a[c])?Utils.isFunction(a[c].addDockedItem)&&(b=a[c])&&Utils.isFunction(b.setBorder)&&b.setBorder({color:"#018A22"}):Utils.isFunction(a[c].resumeBorder)&&a[c].resumeBorder())};
DockableObject.prototype._dock=function(a){if(a&&Utils.isFunction(a.addDockedItem)){if(this.dockTarget)this.dockTarget.removeDockedItem(this),this.dockTarget=null;this.dockTarget=a;this.dockTarget.addDockedItem(this);this.docked=!0;var a=this.x+this.width/2,b=this.y+this.height/2,c=[0,0,0,0];c[0]=Math.abs(a-this.dockTarget.x);c[1]=Math.abs(a-(this.dockTarget.x+this.dockTarget.width));c[2]=Math.abs(b-this.dockTarget.y);c[3]=Math.abs(b-(this.dockTarget.y+this.dockTarget.height));this.posName=["L","R",
"T","B"][Utils.minIndex(c)];this.offsetX=this.x-this.dockTarget.x;this.offsetY=this.y-this.dockTarget.y}};var ContextMenu=function(a,b){this.engine=a;this.id=Quark.UIDUtil.createUID("context-menu");if(!document.getElementById(this.id)){var c=this,d=['<ul class="ctx-menu" id="'+this.id+'">'];if(b)for(var e=0;e<b.length;e++)d.push(['<li class="',b[e].className,'" action="',b[e].action,'">',b[e].text,"</li>"].join(""));d.push("</ul>");$("body").append(d.join("")).click(function(){c.hide()});this.menuDom=document.getElementById(this.id);$("ul.ctx-menu li").bind("mouseenter",function(){var a=$(this);a.hasClass("sp")||
a.addClass("curr")}).bind("mouseleave",function(){var a=$(this);a.hasClass("sp")||a.removeClass("curr")});$("ul.ctx-menu li").click(function(){var a=$(this);if(a.hasClass("delete")){var b=c.engine.getSelected();if(b&&b.length!=0){var d=b.length;if(confirm("\u662f\u5426\u786e\u5b9a\u5220\u9664\u8fd9\u4e9b\u5bf9\u8c61\uff1f"))for(a=0;a<d;a++){var e=b[a];e&&Utils.isFunction(e.remove)&&e.remove()}}}else if(a.hasClass("connection"))if((b=c.engine.getSelected())&&b.length==1&&b[0].canBeConnected)c.engine.addShadowFlow({removeOnComplete:!0},
b[0],b[0].parent);else{d=c.engine.stage.children.slice(0);for(a=0;a<d.length;a++)e=d[a],Element._isActivity(e)&&e.baseType==="container"&&(b=e.getSelected())&&b.length>0&&c.engine.addShadowFlow({removeOnComplete:!0},b[0],e)}else a.attr("action")=="saveAsImage"?c.engine.saveAsImage():a.attr("action")&&c.addNode("add"+a.attr("action"))})}this.eventPos={};this.isShow=!1};
ContextMenu.prototype={menuDom:null,engine:null,addNode:function(a){var b=this.engine.getSelectedNodes();if(!b||b.length==0){var c={x:this.eventPos?this.eventPos.x:$(this.menuDom).offset().left-$(this.engine.container).offset().left,y:this.eventPos?this.eventPos.y:$(this.menuDom).offset().top-$(this.engine.container).offset().top};this.engine[a](c)}else{b=b[0];c={x:b.x+b.width+80,y:b.y+b.height/2-30};c=this.engine[a](c,b.parent);c.y=b.y+b.height/2-c.height/2;for(var d=!1,e=0;e<b.parent.children.length;e++){var f=
b.parent.children[e];f.id!=b.id&&f.id!=c.id&&Utils.isFunction(f.boxCrossed)&&f.boxCrossed(c)&&(c.y+=f.height,d=!0)}if(d&&(c.x+c.width>b.parent.width||c.y+c.height>b.parent.height))d={x:c.x,y:c.y},b.parent.removeChild(c),this.engine[a](d,b.parent);this.engine.addSequenceFlow({startNode:b,endNode:c});b.state="none";b.selected=!1;b.selectorPainter.visible=!1}},showAt:function(a){if(this.menuDom){this.eventPos=Utils.epos(a);var a=this.eventPos.x+$(this.engine.container).offset().left+(Utils.isIE7||Utils.isIE6?
-30:0),b=this.eventPos.y+$(this.engine.container).offset().top,c=this.eventPos.x+$(this.menuDom).width(),d=this.eventPos.y+$(this.menuDom).height();c<=$(this.engine.container).width()&&d<=$(this.engine.container).height()?$(this.menuDom).css({left:a,top:b}).slideDown():c<=$(this.engine.container).width()&&d>$(this.engine.container).height()?$(this.menuDom).css({left:a,top:b-(d-$(this.engine.container).height())}).show():c>$(this.engine.container).width()&&d<=$(this.engine.container).height()?$(this.menuDom).css({left:a-
(c-$(this.engine.container).width()),top:b}).show():c>$(this.engine.container).width()&&d>$(this.engine.container).height()&&$(this.menuDom).css({left:a-(c-$(this.engine.container).width()),top:b-(d-$(this.engine.container).height())}).slideDown();this.isShow=!0}},hide:function(){$(this.menuDom).hide();this.isShow=!1}};(function(){window.lastMouseDownTarget=null;$(document).bind("mousedown",function(a){window.lastMouseDownTarget=a.target})})();
var Engine=function(a){(!a||!a.selector)&&alert("\u53c2\u6570\u4e0d\u8db3\uff01");this.options=a;var b=$(a.selector);this.container=b.get(0);a.fit?(this.width=b.parent().innerWidth(),this.height=b.parent().innerHeight(),b.css({width:this.width,height:this.height})):(this.width=b.innerWidth(),this.height=b.innerHeight());this.canvas=Quark.createDOM("canvas",{width:this.width,height:this.height,style:{position:"absolute",zIndex:1E3,background:"transparent"}});this.canvas.engine=this;this.container.appendChild(this.canvas);
this.raw=a.raw||{id:Quark.UIDUtil.createUID("canvas")};this.id=this.raw.id;this.context=new Quark.CanvasContext({canvas:this.canvas});this.stage=new Q.Stage({context:this.context,width:this.width,height:this.height});this.timer=null;this.timer=Utils.isIE?new Q.Timer(1E3/30):new Q.Timer(40);this.timer.addListener(this.stage);this.timer.start();this.em=new Q.EventManager;b=["mouseup","mousedown","mousemove","dblclick","keydown","contextmenu","click"];this.em.registerStage(this.stage,b,!0,!0);var c=
this;this.stage.addEventListener(b[0],function(a){c.onMouseUp(a)});this.stage.addEventListener(b[1],function(a){window.lastMouseDownTarget=a.target;c.onMouseDown(a)});this.stage.addEventListener(b[2],function(a){c.onMouseMove(a)});this.stage.addEventListener(b[3],function(a){c.onDblClick(a)});Utils.isIE8m?this.stage.addEventListener(b[4],function(a){c.onKeyDown(a)}):$(document).bind(b[4],function(a){if(window.lastMouseDownTarget==c.canvas)c.onKeyDown(a)});this.stage.addEventListener(b[5],function(a){c.onContextMenu(a)});
this.stage.addEventListener(b[6],function(a){c.onClick(a)});this.menu=a.menu?a.menu:new ContextMenu(this)};Engine.prototype.container=null;Engine.prototype.width=0;Engine.prototype.height=0;Engine.prototype.canvas=null;Engine.prototype.stage=null;Engine.prototype.context=null;Engine.prototype.timer=null;Engine.prototype.em=null;Engine.prototype.action="none";Engine.prototype.readonly=!1;Engine.prototype.mute=!1;Engine.prototype.menu=null;
Engine.prototype.setWidth=function(a){this.width=a;this.canvas.width=a;this.canvas.style.width=a+"px";this.stage.width=a;if(this.container)this.container.style.width=a+"px"};Engine.prototype.setHeight=function(a){this.height=a;this.canvas.height=a;this.canvas.style.height=a+"px";this.stage.height=a;if(this.container)this.container.style.height=a+"px"};Engine.prototype.setAction=function(a){this.action=a;this.action=="addConnection"?this.addShadowFlow():this._removeShadow()};
Engine.prototype.setRaw=function(a){this.raw=a||{id:Quark.UIDUtil.createUID("canvas")};this.id=this.raw.id};Engine.prototype.getRaw=function(){return this.raw};Engine.prototype._removeShadow=function(){var a=this.stage.getChildAt(0);if(a&&a.baseType=="shadow")a.overNode&&Utils.isFunction(a.overNode.resumeBorder)&&a.overNode.resumeBorder(),this.stage.removeChild(a),this.stage.context.canvas.style.cursor="default"};
Engine.prototype.saveAsImage=function(){var a=this.canvas.toDataURL("image/png").replace("image/png",'image/octet-stream;Content-Disposition:attachment;filename="canvas.png"');window.location.href=a};
Engine.prototype.onMouseDown=function(a){if(!this.readonly){if(Utils.isRight(a))this.action="none",this._removeShadow();if(this.action!="none"&&this.action!="addConnection"&&Utils.isFunction(this[this.action])){this[this.action].call(this,a);this.action="none";return}}if(!this.mute&&this.action=="none"){for(var b=this.stage.children.slice(0),c=0,d=b.length;c<d;c++){var e=b[c];if(Utils.isFunction(e.onMouseDown)&&(e.onMouseDown(a),e.baseType=="shadow"&&a.cancelBubble))break}!a.cancelBubble&&Utils.isLeft(a)&&
this.stage.addChildAt(ShadowBox.create(a),0)}};Engine.prototype.onMouseMove=function(a){if(!this.readonly){var b=Utils.epos(a),c="x : "+b.x;c+="  y : "+b.y;$("#pos").html(c);for(var b=this.stage.children.slice(0),c=0,d=b.length;c<d;c++){var e=b[c];if(Utils.isFunction(e.onMouseMove)&&(e.onMouseMove(a),a.cancelBubble))break}if(!a.cancelBubble)document.body.style.cursor="default"}};
Engine.prototype.onMouseUp=function(a){if(!this.readonly)for(var b=this.stage.children.slice(0),c=0,d=b.length;c<d;c++){var e=b[c];if(Utils.isFunction(e.onMouseUp)&&(e.onMouseUp(a),a.cancelBubble))break}};Engine.prototype.onDblClick=function(a){if(!this.readonly)for(var b=this.stage.children.slice(0),c=0,d=b.length;c<d;c++){var e=b[c];if(Utils.isFunction(e.onDblClick)&&(e.onDblClick(a),a.cancelBubble))break}};
Engine.prototype.onKeyDown=function(a){if(!this.readonly){if(a.keyCode===Quark.KEY.DELETE){for(var b=this.stage.children,c=!1,d=0;d<b.length;d++)if(b[d]&&(b[d].selected||Utils.isFunction(b[d].getSelected)&&b[d].getSelected())){c=!0;break}if(c&&!confirm("\u786e\u5b9a\u8981\u5220\u9664\u9009\u4e2d\u7684\u5bf9\u8c61\u5417\uff1f"))return}else if(a.keyCode==Quark.KEY.ESC)this.action="none",this._removeShadow();else if(a.keyCode==Quark.KEY.A&&(!Utils.isMac&&a.ctrlKey||Utils.isMac&&a.metaKey)){b=this.stage.children.slice(0);
d=0;for(c=b.length;d<c;d++){var e=b[d];Element._isActivity(e)&&e.select()}Utils.isIE8m||a.preventDefault();return!1}b=this.stage.children.slice(0);d=0;for(c=b.length;d<c;d++)if(e=b[d],Utils.isFunction(e.onKeyDown)&&(e.onKeyDown(a),a.cancelBubble))break}};Engine.prototype.onContextMenu=function(a){if(this.readonly)return!1;this.menu&&this.menu.showAt(a);return!1};
Engine.prototype.onClick=function(a){if(!this.mute){var b=this.getSelected();!b||b.length===0?(this.menu.hide(),this.options.listeners&&Utils.isFunction(this.options.listeners.click)&&this.options.listeners.click.call(this,a)):this.options.listeners&&this.options.listeners.click&&b&&Utils.isFunction(this.options.listeners.click)&&(b.length==1?this.options.listeners.click.call(this,a,b[0]):b.length==0?this.options.listeners.click.call(this,a):this.options.listeners.click.call(this,a,b))}};
Engine.prototype.getSelected=function(){for(var a=this.stage.children.slice(0),b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.selected&&b.push(e);if(Utils.isFunction(e.getSelected)&&(e=e.getSelected()))for(var f=0;f<e.length;f++)b.push(e[f])}return b};Engine.prototype.getSelectedNodes=function(){for(var a=this.stage.children.slice(0),b=[],c=0,d=a.length;c<d;c++){var e=a[c];if(Element._isActivity(e)&&(e.selected&&b.push(e),Utils.isFunction(e.getSelectedNodes)&&(e=e.getSelectedNodes())))for(var f=0;f<e.length;f++)b.push(e[f])}return b};
Engine.prototype.getNodes=function(){for(var a=this.stage.children.slice(0),b=[],c=0,d=a.length;c<d;c++){var e=a[c];if(Element._isActivity(e)&&(b.push(e),Utils.isFunction(e.getNodes)&&(e=e.getNodes())))for(var f=0;f<e.length;f++)b.push(e[f])}return b};Engine.prototype.setActive=function(a,b){var c=this.getNodes();if(c&&!(c.length==0||!a||a.length===0))for(var d=0;d<c.length;d++)for(var e=0;e<a.length;e++)c[d].id===a[e]&&Utils.isFunction(c[d].setActive)&&c[d].setActive(a[e],b)};
Engine.prototype.deactiveAll=function(){for(var a=this.getNodes(),b=0;b<a.length;b++)Utils.isFunction(a[b].setActive)&&a[b].setActive(!1)};Engine.prototype.setReadonly=function(a){this.readonly=a};Engine.prototype.setMute=function(a){this.mute=a};Engine.prototype.clear=function(){this.stage.removeAllChildren()};
Engine.prototype.byId=function(a,b){if(a){var c;c=b?b.children.slice(0):this.stage.children.slice(0);for(var d=0;d<c.length;d++)if(c[d].id===a)return c[d];else if(c[d].rawType==="SubProcess"){var e=this.byId(a,c[d]);if(e)return e}}};Engine.prototype.addShadowFlow=function(a,b,c){a=ShadowFlow.create(a,b);c?c.addChildAt(a,c.startIndex):this.stage.addChildAt(a,0);this.action="none";return a};
Engine.prototype.getRect=function(){var a=this.stage.children.slice(0),b=Utils.max(a,"x"),b=b?b.x+b.width:this.width,a=Utils.max(a,"y");return{x:0,y:0,width:b,height:a?a.y+a.height:this.height}};Engine.prototype._doAddArgs=function(a){var b={},b=a.eventX||a.offsetX?{x:a.offsetX||a.eventX,y:a.offsetY||a.eventY}:a;if(!b.x)b.x=0;if(!b.y)b.y=0;return b};
Engine.prototype._addToCt=function(a,b,c){for(var d=this.stage.children.slice(0),e=!1,f=0;f<d.length;f++){var h=d[f];if(h.baseType=="container"&&h.hitTest(b,c)){a.x=b-h.x;a.y=c-h.y;h.addItem(a);e=!0;break}}return e};
Engine.prototype._addAcitivty=function(a,b,c){var b=this._doAddArgs(b),d=null;try{if(d=eval(a),!d||!Utils.isFunction(d.create))return Q.trace("\u65e0\u6cd5\u521b\u5efa"+a+", \u6216\u8005\u6ca1\u6709create\u51fd\u6570\uff01"),null}catch(e){return Q.trace(e),null}a=d.create(b);d=!1;c?(c.addChild(a),d=!0):d=this._addToCt(a,b.x,b.y);d||this.stage.addChild(a);return a};var ActivityEngine=function(a){if(!a.menu)a.menu=new ContextMenu(this,[{className:"start-event",action:"StartEvent",text:"\u5f00\u59cb\u4e8b\u4ef6"},{className:"end-event",action:"EndEvent",text:"\u7ed3\u675f\u4e8b\u4ef6"},{className:"timer",action:"TimerEvent",text:"\u8ba1\u65f6\u5668\u4e8b\u4ef6"},{className:"user-task",action:"UserTask",text:"\u7528\u6237\u4efb\u52a1"},{className:"parallel-gateway",action:"ParallelGateway",text:"\u5e73\u884c\u7f51\u5173"},{className:"exclusive-gateway",action:"ExclusiveGateway",
text:"\u4e92\u65a5\u7f51\u5173"},{className:"connection",action:"",text:"\u8fde\u63a5\u7ebf"},{className:"subprocess",action:"SubProcess",text:"\u5b50\u6d41\u7a0b"},{className:"sp",action:"",text:""},{className:"delete",action:"",text:"\u5220\u9664"},{className:"sp",action:"",text:""},{className:"savepng",action:"saveAsImage",text:"\u5bfc\u51fa\u56fe\u7247"}]);ActivityEngine.superClass.constructor.call(this,a)};Q.inherit(ActivityEngine,Engine);
ActivityEngine.prototype.addUserTask=function(a,b){return this._addAcitivty("UserTask",a,b)};ActivityEngine.prototype.addServiceTask=function(a,b){return this._addAcitivty("ServiceTask",a,b)};ActivityEngine.prototype.addScriptTask=function(a,b){return this._addAcitivty("ScriptTask",a,b)};ActivityEngine.prototype.addSubProcess=function(a,b){return this._addAcitivty("SubProcess",a,b)};ActivityEngine.prototype.addParallelGateway=function(a,b){return this._addAcitivty("ParallelGateway",a,b)};
ActivityEngine.prototype.addExclusiveGateway=function(a,b){return this._addAcitivty("ExclusiveGateway",a,b)};ActivityEngine.prototype.addEndEvent=function(a,b){return this._addAcitivty("EndEvent",a,b)};ActivityEngine.prototype.addStartEvent=function(a,b){return this._addAcitivty("StartEvent",a,b)};ActivityEngine.prototype.addErrorEndEvent=function(a,b){return this._addAcitivty("ErrorEndEvent",a,b)};ActivityEngine.prototype.addTimerEvent=function(a,b){return this._addAcitivty("TimerEvent",a,b)};
ActivityEngine.prototype.addShadowFlow=function(a,b,c){if(b&&b.canBeConnected)a||(a={}),a.connectionCreated=function(a){a.id=Quark.UIDUtil.createUID("sequenceFlow");a.rawType="SequenceFlow";a.rawObject=SequenceFlow.prototype.rawObject},ActivityEngine.superClass.addShadowFlow.call(this,a,b,c)};ActivityEngine.prototype.addSequenceFlow=function(a){var b={x:0,y:0,autoSize:!0};Q.merge(b,a);b=SequenceFlow.create(b);a.startNode&&a.startNode.parent.addChild(b);return b};
ActivityEngine.prototype.rawObject=function(){if(!this.raw.process_id)this.raw.process_id="process";if(!this.raw.process_namespace)this.raw.process_namespace="http://www.activiti.org/processdef";for(var a={resourceId:this.id,properties:this.raw,stencil:{id:"BPMNDiagram"},bounds:{lowerRight:{x:this.width,y:this.height},upperLeft:{x:0,y:0}},stencilset:{url:"",namespace:"http://b3mn.org/stencilset/bpmn2.0#"},ssextensions:[]},b=[],c=this.stage.children.slice(0),d=0;d<c.length;d++)c[d].rawType=="SubProcess"&&
!c[d].maximized&&c[d].maximize();for(d=0;d<c.length;d++)Utils.isFunction(c[d].rawObject)&&b.push(c[d].rawObject());a.childShapes=b;b=this.getNodes();c={};for(d=0;d<b.length;d++)if(b[d]&&b[d].raw&&b[d].raw.defaultFlow)c[b[d].id]=b[d].raw.defaultFlow;a.properties.defaultFlowDefinitions=c;return a};var SequenceFlow=function(a){SequenceFlow.superClass.constructor.call(this,a);this.id=a.id||Quark.UIDUtil.createUID("sequenceFlow");this.rawType="SequenceFlow"};Q.inherit(SequenceFlow,AbstractConnection);SequenceFlow.create=function(a){return new SequenceFlow(a)};
SequenceFlow.prototype.rawObject=function(){for(var a=[],b=0;b<this.points.length;b++)b==0?a.push({x:this.startNode.width/2,y:this.startNode.height/2}):b==this.points.length-1?a.push({x:this.endNode.width/2,y:this.endNode.height/2}):a.push(this.points[b]);return{resourceId:this.id,properties:{name:this.name,documentation:this.raw.documentation||"",conditionsequenceflow:this.raw.conditionsequenceflow||"",executionlisteners:this.raw.executionlisteners||{},defaultflow:this.defaultFlow||"None",conditionalflow:this.conditionFlow||
"None"},stencil:{id:this.rawType},childShapes:[],outgoing:this.getOutgoing(),bounds:this.getBounds(),dockers:a,target:{resourceId:this.endNode.id}}};var UserTask=function(a){UserTask.superClass.constructor.call(this,a);this.rawType="UserTask";this.icon=a.icon||Icons.userTask;this.name=a.name||Activity.userTask};Q.inherit(UserTask,AbstractTask);UserTask.create=function(a){var b={id:Quark.UIDUtil.createUID("userTask"),autoSize:!0};Q.merge(b,a);return new UserTask(b)};
UserTask.prototype.rawObject=function(){return{bounds:this.getBounds(),childShapes:[],dockers:[],outgoing:this.getOutgoing(),properties:{asynchronousdefinition:this.raw.asynchronousdefinition===!0?"Yes":"No",documentation:this.raw.documentation||"",duedatedefinition:this.raw.duedatedefinition,exclusivedefinition:this.raw.exclusivedefinition===!0?"Yes":"No",formkeydefinition:this.raw.formkeydefinition||"",formproperties:this.raw.formproperties,isforcompensation:this.raw.isforcompensation||"false",
looptype:this.raw.looptype||"None",name:this.name,prioritydefinition:this.raw.prioritydefinition,tasklisteners:this.raw.tasklisteners||{},executionlisteners:this.raw.executionlisteners||{},usertaskassignment:this.raw.usertaskassignment,defaultflow:this.raw.defaultFlow},resourceId:this.id,stencil:{id:this.rawType}}};var ServiceTask=function(a){ServiceTask.superClass.constructor.call(this,a);this.rawType="ServiceTask";this.icon=a.icon||Icons.serviceTask;this.name=a.name||Activity.serviceTask};Q.inherit(ServiceTask,AbstractTask);ServiceTask.create=function(a){var b={id:Quark.UIDUtil.createUID("serviceTask"),width:120,height:60,autoSize:!0};Q.merge(b,a);return new ServiceTask(b)};
ServiceTask.prototype.rawObject=function(){return{resourceId:this.id,properties:{asynchronousdefinition:this.raw.asynchronousdefinition||"No",documentation:this.raw.documentation||"",duedatedefinition:this.raw.dueDate,exclusivedefinition:this.raw.exclusiveDefinition||"Yes",isforcompensation:this.raw.isforcompensation||"false",looptype:this.raw.looptype||"None",name:this.name,prioritydefinition:this.raw.prioritydefinition,tasklisteners:this.raw.taskListeners||{},executionlisteners:this.raw.executionlisteners||
{},servicetaskclass:this.raw.servicetaskclass,servicetaskexpression:this.raw.servicetaskexpression,servicetaskdelegateexpression:this.raw.servicetaskdelegateexpression,servicetaskresultvariable:this.raw.servicetaskresultvariable||"",servicetaskfields:{items:this.raw.servicetaskfields?this.raw.servicetaskfields:[],totalCount:this.raw.servicetaskfields?this.raw.servicetaskfields.length:0}},stencil:{id:this.rawType},childShapes:[],outgoing:this.getOutgoing(),bounds:this.getBounds(),dockers:[]}};var StartEvent=function(a){StartEvent.superClass.constructor.call(this,a);this.rawType="StartNoneEvent";this.icon=a.icon||Icons.startEvent;this.name=a.name||Activity.startEvent};Q.inherit(StartEvent,AbstractEvent);StartEvent.create=function(a){var b={id:Quark.UIDUtil.createUID("startEvent"),autoSize:!0};Q.merge(b,a);return new StartEvent(b)};
StartEvent.prototype.rawObject=function(){return{resourceId:this.id,properties:{name:this.name,documentation:this.raw.documentation||"",formproperties:this.raw.formproperties,initiator:this.raw.initiator,formkeydefinition:this.raw.formkeydefinition||"",executionlisteners:this.raw.executionlisteners||{}},stencil:{id:this.rawType},childShapes:[],outgoing:this.getOutgoing(),bounds:this.getBounds(),dockers:[]}};var EndEvent=function(a){EndEvent.superClass.constructor.call(this,a);this.rawType="EndNoneEvent";this.icon=a.icon||Icons.endEvent;this.name=a.name||Activity.endEvent};Q.inherit(EndEvent,AbstractEvent);EndEvent.create=function(a){var b={id:Quark.UIDUtil.createUID("endNoneEvent"),autoSize:!0};Q.merge(b,a);return new EndEvent(b)};
EndEvent.prototype.rawObject=function(){return{bounds:this.getBounds(),outgoing:[],properties:{documentation:this.raw.documentation||"",name:this.name,executionlisteners:this.raw.executionlisteners||{}},resourceId:this.id,stencil:{id:this.rawType}}};var ParallelGateway=function(a){ParallelGateway.superClass.constructor.call(this,a);this.rawType="ParallelGateway";this.icon=a.icon||Icons.parallelGateway;this.name=a.name||Activity.parallelGateway};Q.inherit(ParallelGateway,AbstractGateway);ParallelGateway.create=function(a){var b={id:Quark.UIDUtil.createUID("parallelGateway"),autoSize:!0};Q.merge(b,a);return new ParallelGateway(b)};
ParallelGateway.prototype.rawObject=function(){return{resourceId:this.id,properties:{name:this.name,documentation:this.raw.documentation||""},stencil:{id:"ParallelGateway"},childShapes:[],outgoing:this.getOutgoing(),bounds:this.getBounds(),dockers:[]}};var ScriptTask=function(a){ScriptTask.superClass.constructor.call(this,a);this.rawType="ScriptTask";this.icon=a.icon||Icons.scriptTask;this.name=a.name||Activity.scriptTask};Q.inherit(ScriptTask,AbstractTask);ScriptTask.create=function(a){var b={id:Quark.UIDUtil.createUID("scriptTask"),width:120,height:60,autoSize:!0};Q.merge(b,a);return new ScriptTask(b)};
ScriptTask.prototype.rawObject=function(){return{resourceId:this.id,properties:{name:this.name,asynchronousdefinition:this.raw.async||"No",documentation:this.raw.documentation||"",duedatedefinition:this.raw.dueDate,exclusivedefinition:this.raw.exclusiveDefinition||"Yes",isforcompensation:this.raw.isforcompensation||"false",looptype:this.raw.looptype||"None",prioritydefinition:this.raw.priorityDefinition,executionlisteners:this.raw.executionlisteners||{},scriptformat:this.raw.scriptformat||"groovy",
scripttext:this.raw.scripttext||""},stencil:{id:this.rawType},childShapes:[],outgoing:this.getOutgoing(),bounds:this.getBounds(),dockers:[]}};var ErrorEndEvent=function(a){ErrorEndEvent.superClass.constructor.call(this,a);this.rawType="EndErrorEvent";this.icon=a.icon||Icons.errorEndEvent;this.name=a.name||Activity.errorEndEvent};Q.inherit(ErrorEndEvent,AbstractEvent);ErrorEndEvent.create=function(a){var b={id:Quark.UIDUtil.createUID("endEvent"),autoSize:!0};Q.merge(b,a);return new ErrorEndEvent(b)};
ErrorEndEvent.prototype.rawObject=function(){return{bounds:this.getBounds(),outgoing:[],properties:{documentation:this.raw.documentation||"",errorrefdefinition:{totalCounts:1,items:[{errorcode:this.raw.errorCode||"aa"}]},name:this.name},resourceId:this.id,stencil:{id:this.rawType}}};var ExclusiveGateway=function(a){ExclusiveGateway.superClass.constructor.call(this,a);this.rawType="ExclusiveGateway";this.icon=a.icon||Icons.exclusiveGateway;this.name=a.name||Activity.exclusiveGateway};Q.inherit(ExclusiveGateway,AbstractGateway);ExclusiveGateway.create=function(a){var b={id:Quark.UIDUtil.createUID("exclusiveGateway"),autoSize:!0};Q.merge(b,a);return new ExclusiveGateway(b)};
ExclusiveGateway.prototype.rawObject=function(){var a=this.getStage().context.canvas.engine,b=this.getOutgoing(),c=!1;if(b){for(var d=0;d<b.length;d++){var e=a.byId(b[d].id);if(e&&e.raw.conditionsequenceflow){c=!0;break}}if(b.length>1&&!c)throw"\u5f53\u6392\u4ed6\u7f51\u5173\u6709\u591a\u4e2a\u51fa\u53e3\u7684\u60c5\u51b5\u4e0b\uff0c\u81f3\u5c11\u4e00\u4e2a\u51fa\u53e3\u9700\u8981\u6761\u4ef6\uff01";}return{resourceId:this.id,properties:{name:this.name,documentation:this.raw.documentation||"",defaultflow:this.raw.defaultFlow},
stencil:{id:"ExclusiveGateway"},childShapes:[],outgoing:this.getOutgoing(),bounds:this.getBounds(),dockers:[]}};var SubProcess=function(a){a||(a={});a.name=a.name||Activity.subProcess;SubProcess.superClass.constructor.call(this,a);this.rawType="SubProcess"};Q.inherit(SubProcess,AbstractContainer);SubProcess.create=function(a){var b={id:Quark.UIDUtil.createUID("subProcess"),width:180,height:90,autoSize:!0,fillColor:"#fdfaea"};Q.merge(b,a);return new SubProcess(b)};
SubProcess.prototype.rawObject=function(){for(var a={bounds:this.getBounds(),childShapes:[],dockers:[],outgoing:this.getOutgoing(),properties:{documentation:this.raw.documentation||"",name:this.name,executionlisteners:this.raw.executionlisteners||{}},resourceId:this.id,stencil:{id:this.rawType}},b=this.children.slice(0),c=0;c<b.length;c++)b[c].rawType&&Utils.isFunction(b[c].rawObject)&&a.childShapes.push(b[c].rawObject());return a};var TimerEvent=function(a){TimerEvent.superClass.constructor.call(this,a);this.rawType="TimerEvent";this.icon=a.icon||Icons.timerEvent;this.name=a.name||Activity.timerEvent};Q.inherit(TimerEvent,DockableObject);TimerEvent.create=function(a){var b={id:Quark.UIDUtil.createUID("timerEvent"),autoSize:!0};Q.merge(b,a);return new TimerEvent(b)};
TimerEvent.prototype.rawObject=function(){var a=null,a=this.docked?"BoundaryTimerEvent":Utils.isFunction(this.getIngoing)&&this.getIngoing().length==0?"StartTimerEvent":"CatchTimerEvent",a={resourceId:this.id,properties:{overrideid:this.id,name:this.name},stencil:{id:a},childShapes:[],outgoing:this.getOutgoing(),bounds:this.getBounds(),dockers:[]};Q.merge(a.properties,this.raw);a.properties.cancelactivity=this.raw.cancelactivity===!0?"Yes":"No";return a};var ActivityAdapter=function(){};
ActivityAdapter.prototype={_extractBpmnType:function(a,b){var c=a.itemDefinitions[b.id];return c?c.itemKind:"EndEvent"},_fixType:function(a,b){if(a==="BoundaryEvent"){if(typeof b.attachedToRef!="undefined"&&typeof b.eventDefinitions!="undefined"&&b.eventDefinitions&&b.eventDefinitions.length>0&&typeof b.eventDefinitions[0].timeDuration!="undefined")return"TimerEvent"}else if(a==="StartEvent"){if(b.eventDefinitions&&b.eventDefinitions.length>0&&typeof b.eventDefinitions[0].timeDuration!="undefined")return"TimerEvent"}else if(a===
"IntermediateCatchEvent")return"TimerEvent";return a},convert:function(a,b,c,d){if(a&&a.flowElements&&a.flowElements.length!=0){var e;e=d?d:c.stage;for(var f=[],h=0;h<a.flowElements.length;h++){var g=a.flowElements[h],i=b.locationMap[g.id];if(i){var j=this._extractBpmnType(b,g),j=this._fixType(j,g),m=i.x;d&&(m=i.x-d.x);var k=i.y;d&&(k=i.y-d.y);i=c._addAcitivty(j,{id:g.id,name:g.name,x:m,y:k,width:i.width,height:i.height},e);i.raw={};i.raw.documentation=g.documentation;i.raw.defaultFlow=g.defaultFlow;
i.raw.initiator=g.initiator;if(j==="UserTask"){if(i.raw.usertaskassignment={items:[]},g.assignee&&i.raw.usertaskassignment.items.push({assignment_type:"assignee",resourceassignmentexpr:g.assignee}),g.candidateUsers&&i.raw.usertaskassignment.items.push({assignment_type:"candidateUsers",resourceassignmentexpr:g.candidateUsers.join(",")}),g.candidateGroups&&i.raw.usertaskassignment.items.push({assignment_type:"candidateGroups",resourceassignmentexpr:g.candidateGroups.join(",")}),i.raw.usertaskassignment.totalCount=
i.raw.usertaskassignment.items.length,i.raw.formkeydefinition=g.formKey,i.raw.exclusivedefinition=!g.notExclusive,i.raw.asynchronousdefinition=g.asynchronous,i.raw.duedatedefinition=g.dueDate,i.raw.prioritydefinition=g.priority,g.taskListeners&&g.taskListeners.length>0){i.raw.tasklisteners={totalCount:g.taskListeners.length,items:[]};for(j=0;j<g.taskListeners.length;j++){var k=g.taskListeners[j],n={task_listener_event_type:k.event};if(k.implementationType==="delegateExpression")n.task_listener_delegate_expression=
k.implementation;else if(k.implementationType==="expression")n.task_listener_expression=k.implementation;else if(k.implementationType==="class")n.task_listener_class=k.implementation;i.raw.tasklisteners.items.push(n)}}}else if(j==="ServiceTask")if(g.implementationType==="class")i.raw.servicetaskclass=g.implementation;else if(g.implementationType==="expression")i.raw.servicetaskexpression=g.implementation;else{if(g.implementationType==="delegateExpression")i.raw.servicetaskdelegateexpression=g.implementation}else if(j===
"ScriptTask")i.raw.scripttext=g.script,i.raw.scriptformat=g.scriptFormat;else if(j==="TimerEvent")f.push({node:i,element:g});else if(j==="StartEvent")i.raw.formkeydefinition=g.formKey,i.raw.initiator=g.initiator;if(typeof g.formProperties!="undefined"&&g.formProperties.length>0)for(m in i.raw.formproperties={totalCount:g.formProperties.length,items:[]},g.formProperties)j=g.formProperties[m],i.raw.formproperties.items.push({formproperty_id:parseInt(j.id)?parseInt(j.id):j.id,formproperty_name:j.name,
formproperty_type:"",formproperty_expression:"",formproperty_variable:""});this.doExecutionListeners(g,i);g.flowElements&&g.flowElements.length>0&&this.convert(g,b,c,i)}}for(h=0;h<f.length;h++)f[h].node.raw.cancelactivity=f[h].element.cancelActivity,f[h].node.raw.timerdurationdefinition=f[h].element.eventDefinitions[0].timeDuration,f[h].node.raw.timerdatedefinition=f[h].element.eventDefinitions[0].timeDate,f[h].node.raw.timercycledefinition=f[h].element.eventDefinitions[0].timeCycle,f[h].element.attachedToRef&&
f[h].element.attachedToRefId&&(g=c.byId(f[h].element.attachedToRefId))&&f[h].node._dock(g);for(h=0;h<a.flowElements.length;h++)if(g=a.flowElements[h],i=b.flowLocationMap[g.id]){d=f=null;m=[];g.sourceRef&&(f=c.byId(g.sourceRef));g.targetRef&&(d=c.byId(g.targetRef));for(j=0;j<i.length;j++)m.push({x:i[j].x,y:i[j].y});if(f&&d){var l=c.addSequenceFlow({startNode:f,endNode:d,points:m,id:g.id},e);l.condition=g.conditionExpression;l.raw.conditionsequenceflow=g.conditionExpression;l.raw.documentation=g.documentation;
l.raw.name=g.name;l.name=g.name;l.isDefault=l.id===l.startNode.raw.defaultFlow}this.doExecutionListeners(g,l)}}},doExecutionListeners:function(a,b){if(a.executionListeners&&a.executionListeners.length>0){b.raw.executionlisteners={totalCount:a.executionListeners.length,items:[]};for(var c=0;c<a.executionListeners.length;c++){var d=a.executionListeners[c],e={execution_listener_event_type:d.event};if(d.implementationType==="delegateExpression")e.execution_listener_delegate_expression=d.implementation;
else if(d.implementationType==="expression")e.execution_listener_expression=d.implementation;else if(d.implementationType==="class")e.execution_listener_class=d.implementation;b.raw.executionlisteners.items.push(e)}}},convertRoot:function(a,b){a.raw.process_id=b.mainProcess.id;a.raw.process_namespace=b.targetNamespace||"http://www.activiti.org/processdef";a.raw.name=b.mainProcess.name||"";a.raw.documentation=b.mainProcess.documentation||"";a.raw.candidateStarterUsers=b.mainProcess.candidateStarterUsers||
"";a.raw.candidateStarterGroups=b.mainProcess.candidateStarterGroups||"";var c=a.raw.candidateStarterUsers;if(Ext.isArray(c)&&c.length>0)a.raw.candidateStarterUsers=c.join(",");c=a.raw.candidateStarterGroups;!Ext.isArray(c)&&typeof c==="string"&&(c=c.split(","));if(c&&c.length>0){for(var d=[],e=0;e<c.length;e++)isNaN(parseInt(c[e]))||d.push(parseInt(c[e]));a.raw.candidateStarterGroups=d}},load:function(a,b){var c={};if(typeof b.processDefinitionId!="undefined"&&b.processDefinitionId!=null)c.processDefinitionId=
b.processDefinitionId;else if(typeof b.deploymentId!="undefined"&&b.deploymentId!=null)c.deploymentId=b.deploymentId;else if(typeof b.key!="undefined"&&b.key!=null)c.key=b.key;else if(typeof b.processInstanceId!="undefined"&&b.processInstanceId!=null)c.processInstanceId=b.processInstanceId;else{alert("\u6ca1\u6709\u8db3\u591f\u7684\u53c2\u6570\uff01");return}var d=this;Ext.Ajax.request({url:b.queryUrl,params:c,method:"GET",success:function(c){c=Ext.decode(c.responseText,!0);!c||c.msg?Utils.isFunction(b.loadFailed)&&
b.loadFailed(c):(a.clear(),new ActivityAdapter,d.convert(c.mainProcess,c,a),Utils.isFunction(b.loadSuccess)&&(d.convertRoot(a,c),b.loadSuccess(c)))},failure:function(a){Utils.isFunction(b.loadFailed)&&b.loadFailed(a)}})}};
